function [BW,prob] = brownMask(I)
%createMask  Threshold RGB image using auto-generated code from colorThresholder app.
%  [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using
%  auto-generated code from the colorThresholder App. The colorspace and
%  minimum/maximum values for each channel of the colorspace were set in the
%  App and result in a binary mask BW and a composite image maskedRGBImage,
%  which shows the original RGB image values under the mask BW.

% Auto-generated by colorThresholder app on 27-Nov-2017
%------------------------------------------------------


% Convert RGB image to chosen color space

% Define thresholds for channel 1 based on histogram settings
channel1Min = min([5.292,3.302,6.799,6.899,6.213,18.197]);
channel1Max = max([22.736,13.254,15.915,24.633,24.564,35.311]);
channel2Min = min([12.792,6.939,5.393,13.032,12.288,10.622]);
channel2Max = max([23.628,24.220,27.226,24.209,24.565,24.385]);
channel3Min = min([6.747,4.271,-2.827,9.771,7.967,-5.630]);
channel3Max = max([20.055,22.704,22.170,23.009,22.971,17.991]);

% Create mask based on chosen histogram thresholds
sliderBW = (I(:,:,1) >= channel1Min ) & (I(:,:,1) <= channel1Max) & ...
    (I(:,:,2) >= channel2Min ) & (I(:,:,2) <= channel2Max) & ...
    (I(:,:,3) >= channel3Min ) & (I(:,:,3) <= channel3Max);
BW = sliderBW;

% Initialize output masked image based on input image.
maskedRGBImage = I;

prob = mean2(BW);
end
