function [BW,prob] = orangeMask(I)
%createMask  Threshold RGB image using auto-generated code from colorThresholder app.
%  [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using
%  auto-generated code from the colorThresholder App. The colorspace and
%  minimum/maximum values for each channel of the colorspace were set in the
%  App and result in a binary mask BW and a composite image maskedRGBImage,
%  which shows the original RGB image values under the mask BW.

% Auto-generated by colorThresholder app on 27-Nov-2017
%------------------------------------------------------


% Convert RGB image to chosen color space
% Define thresholds for channel 1 based on histogram settings
channel1Min = min([21.392,22.887,23.021]);%,44.471,43.079]);
channel1Max = max([53.953,43.552,42.130]);%,86.602,85.489]);
channel2Min = min([25.554,17.716,20.934]);%20.836,19.446
channel2Max = max([36.544,34.964,37.935]);%,54.334,52.519
channel3Min = min([28.140,27.798,27.560]);%,13.888,4.916
channel3Max = max([43.312,43.065,39.207]);%,44.819,43.158]);

% Create mask based on chosen histogram thresholds
sliderBW = (I(:,:,1) >= channel1Min ) & (I(:,:,1) <= channel1Max) & ...
    (I(:,:,2) >= channel2Min ) & (I(:,:,2) <= channel2Max) & ...
    (I(:,:,3) >= channel3Min ) & (I(:,:,3) <= channel3Max);
BW = sliderBW;

% Initialize output masked image based on input image.
maskedRGBImage = I;

% Set background pixels where BW is false to zero.

prob = mean2(BW);
end
