function [BW,prob] = redMask(I)
%createMask  Threshold RGB image using auto-generated code from colorThresholder app.
%  [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using
%  auto-generated code from the colorThresholder App. The colorspace and
%  minimum/maximum values for each channel of the colorspace were set in the
%  App and result in a binary mask BW and a composite image maskedRGBImage,
%  which shows the original RGB image values under the mask BW.

% Auto-generated by colorThresholder app on 27-Nov-2017
%------------------------------------------------------


% Convert RGB image to chosen color space

channel1Min = min([50.539,16.138,11.075]);
channel1Max = max([57.012,36.362,53.419]);
channel2Min = min([29.298,23.610,25.797]);
channel2Max = max([51.748,43.127,43.638]);
channel3Min = min([13.299,8.851,14.126]);
channel3Max = max([48.127,27.087,39.604]);


% Create mask based on chosen histogram thresholds
sliderBW = (I(:,:,1) >= channel1Min ) & (I(:,:,1) <= channel1Max) & ...
    (I(:,:,2) >= channel2Min ) & (I(:,:,2) <= channel2Max) & ...
    (I(:,:,3) >= channel3Min ) & (I(:,:,3) <= channel3Max);
BW = sliderBW;

% Initialize output masked image based on input image.
maskedRGBImage = I;

prob = mean2(BW);
end
